// source: subscription.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() { return this || window || global || self || Function('return this')(); }).call(null);

var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.myapp.Subscription', null, global);
goog.exportSymbol('proto.myapp.Subscription.SubscriptionStatus', null, global);
goog.exportSymbol('proto.myapp.SubscriptionFrequency', null, global);
goog.exportSymbol('proto.myapp.SubscriptionRequest', null, global);
goog.exportSymbol('proto.myapp.SubscriptionResponse', null, global);
goog.exportSymbol('proto.myapp.SubscriptionResponse.SubscriptionResponseType', null, global);
goog.exportSymbol('proto.myapp.User', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.myapp.Subscription = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.myapp.Subscription.repeatedFields_, null);
};
goog.inherits(proto.myapp.Subscription, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.myapp.Subscription.displayName = 'proto.myapp.Subscription';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.myapp.SubscriptionRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.myapp.SubscriptionRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.myapp.SubscriptionRequest.displayName = 'proto.myapp.SubscriptionRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.myapp.SubscriptionResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.myapp.SubscriptionResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.myapp.SubscriptionResponse.displayName = 'proto.myapp.SubscriptionResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.myapp.SubscriptionFrequency = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.myapp.SubscriptionFrequency, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.myapp.SubscriptionFrequency.displayName = 'proto.myapp.SubscriptionFrequency';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.myapp.User = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.myapp.User, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.myapp.User.displayName = 'proto.myapp.User';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.myapp.Subscription.repeatedFields_ = [4,5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.myapp.Subscription.prototype.toObject = function(opt_includeInstance) {
  return proto.myapp.Subscription.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.myapp.Subscription} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.myapp.Subscription.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    amount: jspb.Message.getFieldWithDefault(msg, 2, 0),
    description: jspb.Message.getFieldWithDefault(msg, 3, ""),
    payeeList: jspb.Message.toObjectList(msg.getPayeeList(),
    proto.myapp.User.toObject, includeInstance),
    payerList: jspb.Message.toObjectList(msg.getPayerList(),
    proto.myapp.User.toObject, includeInstance),
    subscriptionFrequency: (f = msg.getSubscriptionFrequency()) && proto.myapp.SubscriptionFrequency.toObject(includeInstance, f),
    status: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.myapp.Subscription}
 */
proto.myapp.Subscription.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.myapp.Subscription;
  return proto.myapp.Subscription.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.myapp.Subscription} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.myapp.Subscription}
 */
proto.myapp.Subscription.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAmount(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 4:
      var value = new proto.myapp.User;
      reader.readMessage(value,proto.myapp.User.deserializeBinaryFromReader);
      msg.addPayee(value);
      break;
    case 5:
      var value = new proto.myapp.User;
      reader.readMessage(value,proto.myapp.User.deserializeBinaryFromReader);
      msg.addPayer(value);
      break;
    case 6:
      var value = new proto.myapp.SubscriptionFrequency;
      reader.readMessage(value,proto.myapp.SubscriptionFrequency.deserializeBinaryFromReader);
      msg.setSubscriptionFrequency(value);
      break;
    case 7:
      var value = /** @type {!proto.myapp.Subscription.SubscriptionStatus} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.myapp.Subscription.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.myapp.Subscription.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.myapp.Subscription} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.myapp.Subscription.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAmount();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPayeeList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.myapp.User.serializeBinaryToWriter
    );
  }
  f = message.getPayerList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.myapp.User.serializeBinaryToWriter
    );
  }
  f = message.getSubscriptionFrequency();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.myapp.SubscriptionFrequency.serializeBinaryToWriter
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      7,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.myapp.Subscription.SubscriptionStatus = {
  ACTIVE: 0,
  PAUSED: 1,
  CANCELED: 2,
  FINISHED: 3
};

/**
 * optional string id = 1;
 * @return {string}
 */
proto.myapp.Subscription.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.myapp.Subscription} returns this
 */
proto.myapp.Subscription.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 amount = 2;
 * @return {number}
 */
proto.myapp.Subscription.prototype.getAmount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.myapp.Subscription} returns this
 */
proto.myapp.Subscription.prototype.setAmount = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string description = 3;
 * @return {string}
 */
proto.myapp.Subscription.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.myapp.Subscription} returns this
 */
proto.myapp.Subscription.prototype.setDescription = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.myapp.Subscription} returns this
 */
proto.myapp.Subscription.prototype.clearDescription = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.myapp.Subscription.prototype.hasDescription = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * repeated User payee = 4;
 * @return {!Array<!proto.myapp.User>}
 */
proto.myapp.Subscription.prototype.getPayeeList = function() {
  return /** @type{!Array<!proto.myapp.User>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.myapp.User, 4));
};


/**
 * @param {!Array<!proto.myapp.User>} value
 * @return {!proto.myapp.Subscription} returns this
*/
proto.myapp.Subscription.prototype.setPayeeList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.myapp.User=} opt_value
 * @param {number=} opt_index
 * @return {!proto.myapp.User}
 */
proto.myapp.Subscription.prototype.addPayee = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.myapp.User, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.myapp.Subscription} returns this
 */
proto.myapp.Subscription.prototype.clearPayeeList = function() {
  return this.setPayeeList([]);
};


/**
 * repeated User payer = 5;
 * @return {!Array<!proto.myapp.User>}
 */
proto.myapp.Subscription.prototype.getPayerList = function() {
  return /** @type{!Array<!proto.myapp.User>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.myapp.User, 5));
};


/**
 * @param {!Array<!proto.myapp.User>} value
 * @return {!proto.myapp.Subscription} returns this
*/
proto.myapp.Subscription.prototype.setPayerList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.myapp.User=} opt_value
 * @param {number=} opt_index
 * @return {!proto.myapp.User}
 */
proto.myapp.Subscription.prototype.addPayer = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.myapp.User, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.myapp.Subscription} returns this
 */
proto.myapp.Subscription.prototype.clearPayerList = function() {
  return this.setPayerList([]);
};


/**
 * optional SubscriptionFrequency subscription_frequency = 6;
 * @return {?proto.myapp.SubscriptionFrequency}
 */
proto.myapp.Subscription.prototype.getSubscriptionFrequency = function() {
  return /** @type{?proto.myapp.SubscriptionFrequency} */ (
    jspb.Message.getWrapperField(this, proto.myapp.SubscriptionFrequency, 6));
};


/**
 * @param {?proto.myapp.SubscriptionFrequency|undefined} value
 * @return {!proto.myapp.Subscription} returns this
*/
proto.myapp.Subscription.prototype.setSubscriptionFrequency = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.myapp.Subscription} returns this
 */
proto.myapp.Subscription.prototype.clearSubscriptionFrequency = function() {
  return this.setSubscriptionFrequency(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.myapp.Subscription.prototype.hasSubscriptionFrequency = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional SubscriptionStatus status = 7;
 * @return {!proto.myapp.Subscription.SubscriptionStatus}
 */
proto.myapp.Subscription.prototype.getStatus = function() {
  return /** @type {!proto.myapp.Subscription.SubscriptionStatus} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {!proto.myapp.Subscription.SubscriptionStatus} value
 * @return {!proto.myapp.Subscription} returns this
 */
proto.myapp.Subscription.prototype.setStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 7, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.myapp.SubscriptionRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.myapp.SubscriptionRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.myapp.SubscriptionRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.myapp.SubscriptionRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    subscriptionId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    payer: (f = msg.getPayer()) && proto.myapp.User.toObject(includeInstance, f),
    payee: (f = msg.getPayee()) && proto.myapp.User.toObject(includeInstance, f),
    createTime: (f = msg.getCreateTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updateTime: (f = msg.getUpdateTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.myapp.SubscriptionRequest}
 */
proto.myapp.SubscriptionRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.myapp.SubscriptionRequest;
  return proto.myapp.SubscriptionRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.myapp.SubscriptionRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.myapp.SubscriptionRequest}
 */
proto.myapp.SubscriptionRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubscriptionId(value);
      break;
    case 3:
      var value = new proto.myapp.User;
      reader.readMessage(value,proto.myapp.User.deserializeBinaryFromReader);
      msg.setPayer(value);
      break;
    case 4:
      var value = new proto.myapp.User;
      reader.readMessage(value,proto.myapp.User.deserializeBinaryFromReader);
      msg.setPayee(value);
      break;
    case 5:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreateTime(value);
      break;
    case 6:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdateTime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.myapp.SubscriptionRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.myapp.SubscriptionRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.myapp.SubscriptionRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.myapp.SubscriptionRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSubscriptionId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPayer();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.myapp.User.serializeBinaryToWriter
    );
  }
  f = message.getPayee();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.myapp.User.serializeBinaryToWriter
    );
  }
  f = message.getCreateTime();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdateTime();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.myapp.SubscriptionRequest.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.myapp.SubscriptionRequest} returns this
 */
proto.myapp.SubscriptionRequest.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string subscription_id = 2;
 * @return {string}
 */
proto.myapp.SubscriptionRequest.prototype.getSubscriptionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.myapp.SubscriptionRequest} returns this
 */
proto.myapp.SubscriptionRequest.prototype.setSubscriptionId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional User payer = 3;
 * @return {?proto.myapp.User}
 */
proto.myapp.SubscriptionRequest.prototype.getPayer = function() {
  return /** @type{?proto.myapp.User} */ (
    jspb.Message.getWrapperField(this, proto.myapp.User, 3));
};


/**
 * @param {?proto.myapp.User|undefined} value
 * @return {!proto.myapp.SubscriptionRequest} returns this
*/
proto.myapp.SubscriptionRequest.prototype.setPayer = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.myapp.SubscriptionRequest} returns this
 */
proto.myapp.SubscriptionRequest.prototype.clearPayer = function() {
  return this.setPayer(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.myapp.SubscriptionRequest.prototype.hasPayer = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional User payee = 4;
 * @return {?proto.myapp.User}
 */
proto.myapp.SubscriptionRequest.prototype.getPayee = function() {
  return /** @type{?proto.myapp.User} */ (
    jspb.Message.getWrapperField(this, proto.myapp.User, 4));
};


/**
 * @param {?proto.myapp.User|undefined} value
 * @return {!proto.myapp.SubscriptionRequest} returns this
*/
proto.myapp.SubscriptionRequest.prototype.setPayee = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.myapp.SubscriptionRequest} returns this
 */
proto.myapp.SubscriptionRequest.prototype.clearPayee = function() {
  return this.setPayee(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.myapp.SubscriptionRequest.prototype.hasPayee = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.Timestamp create_time = 5;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.myapp.SubscriptionRequest.prototype.getCreateTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 5));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.myapp.SubscriptionRequest} returns this
*/
proto.myapp.SubscriptionRequest.prototype.setCreateTime = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.myapp.SubscriptionRequest} returns this
 */
proto.myapp.SubscriptionRequest.prototype.clearCreateTime = function() {
  return this.setCreateTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.myapp.SubscriptionRequest.prototype.hasCreateTime = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.Timestamp update_time = 6;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.myapp.SubscriptionRequest.prototype.getUpdateTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 6));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.myapp.SubscriptionRequest} returns this
*/
proto.myapp.SubscriptionRequest.prototype.setUpdateTime = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.myapp.SubscriptionRequest} returns this
 */
proto.myapp.SubscriptionRequest.prototype.clearUpdateTime = function() {
  return this.setUpdateTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.myapp.SubscriptionRequest.prototype.hasUpdateTime = function() {
  return jspb.Message.getField(this, 6) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.myapp.SubscriptionResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.myapp.SubscriptionResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.myapp.SubscriptionResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.myapp.SubscriptionResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    subscriptionId: jspb.Message.getFieldWithDefault(msg, 2, ""),
    payer: (f = msg.getPayer()) && proto.myapp.User.toObject(includeInstance, f),
    payee: (f = msg.getPayee()) && proto.myapp.User.toObject(includeInstance, f),
    response: jspb.Message.getFieldWithDefault(msg, 5, 0),
    description: jspb.Message.getFieldWithDefault(msg, 6, ""),
    createTime: (f = msg.getCreateTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updateTime: (f = msg.getUpdateTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.myapp.SubscriptionResponse}
 */
proto.myapp.SubscriptionResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.myapp.SubscriptionResponse;
  return proto.myapp.SubscriptionResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.myapp.SubscriptionResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.myapp.SubscriptionResponse}
 */
proto.myapp.SubscriptionResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSubscriptionId(value);
      break;
    case 3:
      var value = new proto.myapp.User;
      reader.readMessage(value,proto.myapp.User.deserializeBinaryFromReader);
      msg.setPayer(value);
      break;
    case 4:
      var value = new proto.myapp.User;
      reader.readMessage(value,proto.myapp.User.deserializeBinaryFromReader);
      msg.setPayee(value);
      break;
    case 5:
      var value = /** @type {!proto.myapp.SubscriptionResponse.SubscriptionResponseType} */ (reader.readEnum());
      msg.setResponse(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 7:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreateTime(value);
      break;
    case 8:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdateTime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.myapp.SubscriptionResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.myapp.SubscriptionResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.myapp.SubscriptionResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.myapp.SubscriptionResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSubscriptionId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPayer();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.myapp.User.serializeBinaryToWriter
    );
  }
  f = message.getPayee();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.myapp.User.serializeBinaryToWriter
    );
  }
  f = message.getResponse();
  if (f !== 0.0) {
    writer.writeEnum(
      5,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getCreateTime();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdateTime();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.myapp.SubscriptionResponse.SubscriptionResponseType = {
  ACCEPT: 0,
  REJECT: 1
};

/**
 * optional string id = 1;
 * @return {string}
 */
proto.myapp.SubscriptionResponse.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.myapp.SubscriptionResponse} returns this
 */
proto.myapp.SubscriptionResponse.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string subscription_id = 2;
 * @return {string}
 */
proto.myapp.SubscriptionResponse.prototype.getSubscriptionId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.myapp.SubscriptionResponse} returns this
 */
proto.myapp.SubscriptionResponse.prototype.setSubscriptionId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional User payer = 3;
 * @return {?proto.myapp.User}
 */
proto.myapp.SubscriptionResponse.prototype.getPayer = function() {
  return /** @type{?proto.myapp.User} */ (
    jspb.Message.getWrapperField(this, proto.myapp.User, 3));
};


/**
 * @param {?proto.myapp.User|undefined} value
 * @return {!proto.myapp.SubscriptionResponse} returns this
*/
proto.myapp.SubscriptionResponse.prototype.setPayer = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.myapp.SubscriptionResponse} returns this
 */
proto.myapp.SubscriptionResponse.prototype.clearPayer = function() {
  return this.setPayer(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.myapp.SubscriptionResponse.prototype.hasPayer = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional User payee = 4;
 * @return {?proto.myapp.User}
 */
proto.myapp.SubscriptionResponse.prototype.getPayee = function() {
  return /** @type{?proto.myapp.User} */ (
    jspb.Message.getWrapperField(this, proto.myapp.User, 4));
};


/**
 * @param {?proto.myapp.User|undefined} value
 * @return {!proto.myapp.SubscriptionResponse} returns this
*/
proto.myapp.SubscriptionResponse.prototype.setPayee = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.myapp.SubscriptionResponse} returns this
 */
proto.myapp.SubscriptionResponse.prototype.clearPayee = function() {
  return this.setPayee(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.myapp.SubscriptionResponse.prototype.hasPayee = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional SubscriptionResponseType response = 5;
 * @return {!proto.myapp.SubscriptionResponse.SubscriptionResponseType}
 */
proto.myapp.SubscriptionResponse.prototype.getResponse = function() {
  return /** @type {!proto.myapp.SubscriptionResponse.SubscriptionResponseType} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.myapp.SubscriptionResponse.SubscriptionResponseType} value
 * @return {!proto.myapp.SubscriptionResponse} returns this
 */
proto.myapp.SubscriptionResponse.prototype.setResponse = function(value) {
  return jspb.Message.setProto3EnumField(this, 5, value);
};


/**
 * optional string description = 6;
 * @return {string}
 */
proto.myapp.SubscriptionResponse.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.myapp.SubscriptionResponse} returns this
 */
proto.myapp.SubscriptionResponse.prototype.setDescription = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.myapp.SubscriptionResponse} returns this
 */
proto.myapp.SubscriptionResponse.prototype.clearDescription = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.myapp.SubscriptionResponse.prototype.hasDescription = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional google.protobuf.Timestamp create_time = 7;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.myapp.SubscriptionResponse.prototype.getCreateTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 7));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.myapp.SubscriptionResponse} returns this
*/
proto.myapp.SubscriptionResponse.prototype.setCreateTime = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.myapp.SubscriptionResponse} returns this
 */
proto.myapp.SubscriptionResponse.prototype.clearCreateTime = function() {
  return this.setCreateTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.myapp.SubscriptionResponse.prototype.hasCreateTime = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional google.protobuf.Timestamp update_time = 8;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.myapp.SubscriptionResponse.prototype.getUpdateTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 8));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.myapp.SubscriptionResponse} returns this
*/
proto.myapp.SubscriptionResponse.prototype.setUpdateTime = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.myapp.SubscriptionResponse} returns this
 */
proto.myapp.SubscriptionResponse.prototype.clearUpdateTime = function() {
  return this.setUpdateTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.myapp.SubscriptionResponse.prototype.hasUpdateTime = function() {
  return jspb.Message.getField(this, 8) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.myapp.SubscriptionFrequency.prototype.toObject = function(opt_includeInstance) {
  return proto.myapp.SubscriptionFrequency.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.myapp.SubscriptionFrequency} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.myapp.SubscriptionFrequency.toObject = function(includeInstance, msg) {
  var f, obj = {
    startDate: jspb.Message.getFieldWithDefault(msg, 1, ""),
    endDate: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.myapp.SubscriptionFrequency}
 */
proto.myapp.SubscriptionFrequency.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.myapp.SubscriptionFrequency;
  return proto.myapp.SubscriptionFrequency.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.myapp.SubscriptionFrequency} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.myapp.SubscriptionFrequency}
 */
proto.myapp.SubscriptionFrequency.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setStartDate(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setEndDate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.myapp.SubscriptionFrequency.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.myapp.SubscriptionFrequency.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.myapp.SubscriptionFrequency} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.myapp.SubscriptionFrequency.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStartDate();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getEndDate();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string start_date = 1;
 * @return {string}
 */
proto.myapp.SubscriptionFrequency.prototype.getStartDate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.myapp.SubscriptionFrequency} returns this
 */
proto.myapp.SubscriptionFrequency.prototype.setStartDate = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string end_date = 2;
 * @return {string}
 */
proto.myapp.SubscriptionFrequency.prototype.getEndDate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.myapp.SubscriptionFrequency} returns this
 */
proto.myapp.SubscriptionFrequency.prototype.setEndDate = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.myapp.User.prototype.toObject = function(opt_includeInstance) {
  return proto.myapp.User.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.myapp.User} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.myapp.User.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.myapp.User}
 */
proto.myapp.User.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.myapp.User;
  return proto.myapp.User.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.myapp.User} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.myapp.User}
 */
proto.myapp.User.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.myapp.User.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.myapp.User.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.myapp.User} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.myapp.User.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.myapp.User.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.myapp.User} returns this
 */
proto.myapp.User.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


goog.object.extend(exports, proto.myapp);
